"""unanswer_db

Revision ID: 50e46ddfbf3a
Revises: a2a5f3a3607b
Create Date: 2024-02-01 12:51:24.191778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e46ddfbf3a'
down_revision: Union[str, None] = 'a2a5f3a3607b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
