"""cool

Revision ID: 635160a96bd0
Revises: 499ef0ccd5c9
Create Date: 2024-01-17 17:59:24.446425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635160a96bd0'
down_revision: Union[str, None] = '499ef0ccd5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'unanswered_question', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unanswered_question', type_='unique')
    # ### end Alembic commands ###
