"""meramaan

Revision ID: 643725afccb2
Revises: d7ddb4b3a565
Create Date: 2024-02-01 16:04:16.940856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643725afccb2'
down_revision: Union[str, None] = 'd7ddb4b3a565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_user_id_fkey', 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key('conversation_user_id_fkey', 'conversation', 'intent', ['user_id'], ['id'])
    # ### end Alembic commands ###
