"""endmigration

Revision ID: d0f27bc99319
Revises: d46c6aa55b1f
Create Date: 2024-02-23 19:54:12.323731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f27bc99319'
down_revision: Union[str, None] = 'd46c6aa55b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intent_id', table_name='intent')
    op.drop_table('intent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_tag', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('question_pattern', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('response_answer', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='intent_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='intent_pkey')
    )
    op.create_index('ix_intent_id', 'intent', ['id'], unique=True)
    # ### end Alembic commands ###
