"""final_migration

Revision ID: d46c6aa55b1f
Revises: 643725afccb2
Create Date: 2024-02-01 16:10:46.352493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46c6aa55b1f'
down_revision: Union[str, None] = '643725afccb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'user_question',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('conversation', 'bot_response',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'bot_response',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('conversation', 'user_question',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
