"""003first

Revision ID: da9b62c95805
Revises: 
Create Date: 2024-01-16 17:07:01.075027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9b62c95805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('is_active'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('password')
    )
    op.add_column(
        'user',
        sa.Column('user_type', sa.Enum('admin', 'normal_user', name='role'), nullable=False)
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_question', sa.String(length=30), nullable=False),
    sa.Column('bot_response', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_response'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('intent'),
    sa.UniqueConstraint('user_question')
    )
    op.create_table('intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_tag', sa.String(length=30), nullable=False),
    sa.Column('question_pattern', sa.String(length=30), nullable=False),
    sa.Column('response_answer', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('question_pattern'),
    sa.UniqueConstraint('question_tag'),
    sa.UniqueConstraint('response_answer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intent')
    op.drop_table('conversation')
    op.drop_table('user')
    # ### end Alembic commands ###
