"""kk

Revision ID: e5259dbc8352
Revises: 8b6aa1b1de22
Create Date: 2024-01-17 19:22:15.381720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5259dbc8352'
down_revision: Union[str, None] = '8b6aa1b1de22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversation_user_id_fkey', 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'intent', ['user_id'], ['id'])
    op.drop_constraint('unanswered_question_user_id_fkey', 'unanswered_question', type_='foreignkey')
    op.create_foreign_key(None, 'unanswered_question', 'intent', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unanswered_question', type_='foreignkey')
    op.create_foreign_key('unanswered_question_user_id_fkey', 'unanswered_question', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key('conversation_user_id_fkey', 'conversation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
